tsntool: add recipes
*update to lsdk 1909 tag
include the following changes:
30a0320 - demos:cnc: add Qci enable/disable operations provide to yang
a27ea6d - demos:cnc: fix the interfaces and bridges types xml getconfig infrormation
ccfc0ae - demos:cnc:add Qci support
50d653b - libtsn: fix compile error
a156db9 - tsntool: correct the command name in help info
6739dcb - libtsn: add optional function to monitor the operation of configuring TSN via libtsn
eadb457 - Add version v0.3 tag
42ee8f3 - libtsn: add qbu get status showing status
a22cdc8 - demos:cnc: update the get-config feedback "interfaces" to "if:interfaces"
495575c - demo:cnc: fix the get-config button out of block when brower pixel low resolution
a411c7c - demo:cnc: fix config-change place and enable for port
3d28bea - qbvset: fix overflow of qbv list
1b424e9 - Makefile : add format-security to fix gcc 9.2 build error fix the below error |main/readinput.c:267:3: error: format not a string |literal and no format arguments [-Werror=format-security]
7ec5761 - cnc: fix the qbv disable setting

Signed-off-by: Chunrong Guo <chunrong.guo@nxp.com>