waffle: Fix x11 build without GBM support
For i.MX 6 and 7, building x11_egl failed with the following:

```
In file included from ../waffle-1.6.0/src/waffle/surfaceless_egl/sl_window.c:35:
../waffle-1.6.0/src/waffle/surfaceless_egl/sl_platform.h:30:10: fatal error: gbm.h: No such file or directory
   30 | #include <gbm.h>
      |          ^~~~~~~
```

The failure is not surprising since i.MX 6 and 7 don't
support GBM. What is surprising is surfaceless_egl is
built even if it is disabled. The meson dependency
for surfaceless_egl was incorrectly tied to x11_egl,
so fix that, plus add a dependency on GBM.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>