imx-vpu-hantro: fix compile time error
GCC-14 set more warnings to errors, demote the ones which trigger to a warning.

Fixes:
| ../../source/h264high/h264decapi.c:1803:22: error: assignment to 'const u8 *' {aka 'const unsigned char *'} from incompatible pointer type 'u32 *' {aka 'unsigned int *'} [-Wincompatible-pointer-types]
|  1803 |             ref_data = ref.virtual_address;
| ../../source/h264high/h264decapi.c:2086:22: error: assignment to 'const u8 *' {aka 'const unsigned char *'} from incompatible pointer type 'u32 *' {aka 'unsigned int *'} [-Wincompatible-pointer-types]
|  2086 |             ref_data = ref.virtual_address;

Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>
(cherry picked from commit df6ff365d3292c9874b055b55e2378ee8307c1fd)