imx-test: Disable stringformat security flags
This fixes following build error:

,----
| pxp_lib_test/pxp_test.c: In function 'main':
| pxp_lib_test/pxp_test.c:541:2: error: format not a string literal and no format arguments [-Werror=format-security]
|   541 |  printf(usage);
|       |  ^~~~~~
`----

Fixes: #506.
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>
Change-Id: Ie6df1a64ba7126967861cb8fc889d4ca6f22b67a
(cherry picked from commit 8a6193807d07edc30fd06e19f475dc7a7c1689b2)