qtbase: Enable wayland knob when in distro features
Mimic the behavior from recipe proper here since we override
packageconfig defaults. With QT 6.7, qtbase built without wayland
support is not sufficient to build rest of QT components e.g. qtwayland
errors out during build/configure

    ERROR: Qt Wayland Client requires QtGui to be build with support for wayland

Therefore add it when wayland is in distro features.

Signed-off-by: Khem Raj <raj.khem@gmail.com>