u-boot-qoriq: add -fgnu89-inline option for gcc5
Fix the below build issues:
  CC      drivers/crypto/fsl/sec.o
  LD      arch/powerpc/cpu/mpc8xxx/built-in.o
arch/powerpc/cpu/mpc8xxx/fdt.o: In function `ld_le16':
../arch/powerpc/include/asm/byteorder.h:12: multiple definition of `ld_le16'

The problem is the change of the default C standard from gnu89 to gnu11
which changes the semantics of 'inline'. The issue is described in the
Porting guide at https://gcc.gnu.org/gcc-5/porting_to.html. Adding the
'-fgnu89-inline' option fixes the issue.

Signed-off-by: Ting Liu <ting.liu@freescale.com>
Acked-by: Otavio Salvador <otavio@ossystems.com.br>
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>