qemu: configure properly check if -lrt is needed
-lrt is needed to avoid the error "undefined reference to
`timer_settime'". add the check in configure.

Backport from http://git.qemu.org/?p=qemu.git
commit: 8bacde8d86a09699207d85d4bab06162aed18dc4

Fix the below build issue:
| ../qemu-timer.o: In function `dynticks_rearm_timer':
| .../qemu/1.0+fsl-r2/git/qemu-timer.c:597: undefined reference to `timer_gettime'
| .../qemu/1.0+fsl-r2/git/qemu-timer.c:610: undefined reference to `timer_settime'
| ../qemu-timer.o: In function `dynticks_stop_timer':
| .../qemu/1.0+fsl-r2/git/qemu-timer.c:583: undefined reference to `timer_delete'
| ../qemu-timer.o: In function `dynticks_start_timer':
| .../qemu/1.0+fsl-r2/git/qemu-timer.c:565: undefined reference to `timer_create'
| ivshmem.o: In function `pci_ivshmem_init':
| .../qemu/1.0+fsl-r2/git/hw/ivshmem.c:720: undefined reference to `shm_open'
| .../qemu/1.0+fsl-r2/git/hw/ivshmem.c:727: undefined reference to `shm_open'
| collect2: error: ld returned 1 exit status
| make[1]: *** [qemu-system-ppc] Error 1
| make: *** [subdir-ppc-softmmu] Error 2
| ERROR: oe_runmake failed
| ERROR: Function failed: do_compile

Yocto 1.4_M4 uses qemu 1.3.1 which includes this fix. So
this issue only appeared to us.

Signed-off-by: Ting Liu <b28495@freescale.com>