imx-gst1.0-plugin: fix build against glibc 2.42
OE-core updated to glibc 2.42. This version no longer provides
termio.h.

Fixes
| ...tools/gplay2/gplay2.c:29:10: fatal error: termio.h: No such file or directory

Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>