recipes-graphics: clutter/cogl: move bbappend to dynamic layers
As it breaks the build on master since [1]. Move bbappend files to
dynamic layers since recipes were moved to meta-gnome

Fixes:

ERROR: No recipes in default available for:
  /home/bdx-iot/ci/meta-freescale/recipes-graphics/clutter/clutter-1.0_%.bbappend
  /home/bdx-iot/ci/meta-freescale/recipes-graphics/cogl/cogl-1.0_%.bbappend

[1] - http://git.openembedded.org/openembedded-core/commit/?id=c4f167d05f58f35a6b94e8dbc4721ab67e7e71eb

Signed-off-by: Pierre-Jean Texier <texier.pj2@gmail.com>