linux-fslc-imx: Fix ParseError due to broken comments
Commit 2862dc5e6279 ("linux-fslc-imx: Bump kernel to LF6.18.2_1.0.0 + stable up to v6.18.24")
accidentally dropped the # in front of the git log comments, breaking
the recipe parsing.

Comment out the list of git commits in this recipe again.

Fixes the below error:
ERROR: ParseError at [..]/meta-freescale/recipes-kernel/linux/linux-fslc-imx_6.18.bb:46: unparsed line: '$ 6e811374f6340 drm/imx: lcdifv3: Fix videomode settings'

Fixes: 2862dc5e6279 ("linux-fslc-imx: Bump kernel to LF6.18.2_1.0.0 + stable up to v6.18.24")
Signed-off-by: Ernest Van Hoecke <ernest.vanhoecke@toradex.com>