vulkan-loader: Fix patch for non-GPU i.MX 8
Building for i.MX 8 without GPU results in a patching error:
```
ERROR: vulkan-loader-1.4.309.0-r0 do_patch: QA Issue: Fuzz detected:

Applying patch 0001-LF-11869-change-mali-wsi-layer-activating-order.patch
patching file loader/loader.c
Hunk #1 succeeded at 3034 with fuzz 1 (offset 128 lines).
Hunk #2 succeeded at 3101 (offset 135 lines).
Hunk #3 succeeded at 3115 (offset 135 lines).

The context lines in the patches can be updated with devtool:

    devtool modify vulkan-loader
    devtool finish --force-patch-refresh vulkan-loader <layer_path>

Don't forget to review changes done by devtool!

Patch log indicates that patches do not apply cleanly. [patch-fuzz]
```

The problem is i.MX 8 without GPU uses the latest Vulkan 1.4.309.0 and
needs that version of the patch, but the recipe provides the older
version of the patch for Vulkan 1.3.275.0.imx.

Use version-specific folders to resolve the mismatch.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>
(cherry picked from commit 8fa7e34f51b88110e54638028a4635f62e44cc0a)