libimxdmabuffer: be explicit about dwl compatibility
PACKAGECONFIG[dwl] injects a direct dependency on imx-vpu-hantro which in itself is
only compatible with (mx8mq-nxp-bsp|mx8mm-nxp-bsp|mx8mp-nxp-bsp)

When configuring a mx8mn based machine (e.g. imx8mn EVK)
the imx-vpu-hantro is skipped as not compatible, but a world build fails with

ERROR: Nothing PROVIDES 'imx-vpu-hantro'
(but /build/meta-freescale/recipes-bsp/libimxdmabuffer/libimxdmabuffer_1.1.2.bb DEPENDS on or otherwise requires it)
imx-vpu-hantro was skipped: incompatible with machine imx8mn-ddr4-evk (not in COMPATIBLE_MACHINE)
imx-vpu-hantro was skipped: incompatible with machine imx8mn-ddr4-evk (not in COMPATIBLE_MACHINE)
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'gstreamer1.0-plugins-imx',
'libimxdmabuffer', 'imx-vpu-hantro']

Fix that by enabling dwl only for the same COMPATIBLE_MACHINE settings as in the imx-vpu-hantro recipe

Signed-off-by: Konrad Weihmann <konrad.weihmann@avnet.eu>