u-boot-imx: Add missing gnutls dependency
Fixes:
```
| /.../tmp/work/imx8mq_evk-fsl-linux/u-boot-imx/2022.04-r0/git/tools/mkeficapsule.c:21:10: fatal error: gnutls/gnutls.h: No such file or directory
|  #include <gnutls/gnutls.h>
|           ^~~~~~~~~~~~~~~~~
```

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>
(cherry picked from commit 4b7afb6b2d7842a9c76c2c88657a7e6da7a6aa53)