Revert "fsl-dynamic-packagearch: fix MACHINE_SOCARCH definition"
This change makes no sense. MACHINE_SOCARCH must include the suffix
that makes the value SOC-specific. Otherwise, errors such as this occur:
```
ERROR: imx-dpu-g2d-2.1.12-r0 do_create_spdx_setscene: Recipe imx-dpu-g2d is trying to install files into a shared area when those files already exist. The files and the manifests listing them are:
  tmp/deploy/spdx/armv8a/packages/libg2d-dev.spdx.json
    (matched in manifest-armv8a-imx-pxp-g2d.create_spdx)
  tmp/deploy/spdx/armv8a/packages/libg2d2.spdx.json
    (matched in manifest-armv8a-imx-pxp-g2d.create_spdx)
```

This reverts commit 6579ce9b77f0036454478b2e07694f7314f97867.