xf86-video-imx-vivante: fix compile by updating to 6.4.0
Using the current HEAD fixes the following compile error:

| vivante_gal/vivante_gal_surface.c:493:38: error: 'gcvPOOL_CONTIGUOUS' undeclared (first use in this function); did you mean 'gcvSURF_CONTIGUOUS'?
|   493 |             surf->mVideoNode.mPool = gcvPOOL_CONTIGUOUS;
|       |                                      ^~~~~~~~~~~~~~~~~~

meta-fsl-bsp-release sets version to 6.4.0.p0.0 for this git hash,
follow that here.

Changelog:
MGS-4783 [#ccc] Integrate EXA patches for 6.4.0 beta

Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>