odp.inc: Fix patch file location
Recipes that include odp.inc but are not named odp fail to find the
patch file added by odp.inc.
```
ERROR: /.../meta-freescale/recipes-extended/odp/odp-counters_git.bb: Unable to get checksum for odp-counters SRC_URI entry 0001-Fix-this-build-error.patch: file could not be found
```

Move the patch file from the recipe-specific directory to the shared
files directory to ensure it can be found by all recipes that include
odp.inc, regardless of recipe name.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>
(cherry picked from commit 1f7f4878f43a7eb5419d946b36c9158bf168253a)