linux-mfgtool.inc: Fix wrong build dependency
This fixes following error:

ERROR: Nothing PROVIDES 'virtual/mfgtool-arm-...-binutils'.

Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>
(cherry picked from commit 7a5f1e14504e43bf41ebb9f36cb56bd71cceab32)