vulkan-loader: Fix library packaging
The logic to move the .so into the main package is incorrect and results
in all libraries being moved to the dev package, causing a QA error like
the following:

```
ERROR: imx-gpu-sdk-5.7.1-r0 do_package_qa: QA Issue: imx-gpu-sdk rdepends on vulkan-loader-dev [dev-deps]
```

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>