piglit: Remove opencl for 6 and 7
The build is broken on Whinlatter:
```
| /usr/src/debug/piglit/1.0+gitr/tests/cl/api/create-command-queue.c:141:(.text+0x148): undefined reference to `clCreateCommandQueueWithProperties'
```

Until recently, piglit for i.MX 6 and 7 was configured without OpenCL.
Now it is set based on the new distro feature opencl. Disable it again
to fix the build.

Signed-off-by: Zelan Zou <zelan.zou@nxp.com>
Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>