vulkan-wsi-layer: add S assignment
Add missing S assignment for walnascar. Fixes build issue:

WARNING: vulkan-wsi-layer-0.0+git-r0 do_unpack: vulkan-wsi-layer: the directory ${WORKDIR}/${BP} (/home/qt/work/build/tmp/work/cortexa55-mx95-poky-linux/vulkan-wsi-layer/0.0+git/vulkan-wsi-layer-0.0+git) pointed to by the S variable doesn't exist - please set S within the recipe to point to where the source has been unpacked t
ERROR: vulkan-wsi-layer-0.0+git-r0 do_patch: Applying patch '0001-MGS-6801-ccc-vkmark-on-wayland.patch' on target directory '/home/qt/work/build/tmp/work/cortexa55-mx95-poky-linux/vulkan-wsi-layer/0.0+git/vulkan-wsi-layer-0.0+git'
CmdError('quilt --quiltrc /home/qt/work/build/tmp/work/cortexa55-mx95-poky-linux/vulkan-wsi-layer/0.0+git/recipe-sysroot-native/etc/quiltrc push', 0, "stdout: Applying patch 0001-MGS-6801-ccc-vkmark-on-wayland.patch
can't find file to patch at input line 19

Signed-off-by: Mikko Gronoff <mikko.gronoff@qt.io>