gst-examples: Refresh 0001-Make-player-examples-installable.patch
The GStreamer 1.28.1 update introduced the following build error:
  ERROR: gst-examples-1.28.1-r0 do_patch: Applying patch '[...]/layers/meta-freescale/recipes-multimedia/gstreamer/gst-examples/0001-Make-player-examples-installable.patch' on target directory '/var/home/vhe/build/bitbake-builds/tdxref-master-qcom/build/tmp/work/cortexa55-mx95-tdx-linux/gst-examples/1.28.1/sources/gst-examples-1.28.1/subprojects/gst-examples'
  CmdError('quilt --quiltrc [...]/build/tmp/work/cortexa55-mx95-tdx-linux/gst-examples/1.28.1/recipe-sysroot-native/etc/quiltrc push', 1, 'stdout: Applying patch 0001-Make-player-examples-installable.patch
  patching file playback/player/gst-play/meson.build
  patching file playback/player/gtk/meson.build
  Hunk #1 FAILED at 20.
  1 out of 1 hunk FAILED -- rejects in file playback/player/gtk/meson.build
  Patch 0001-Make-player-examples-installable.patch does not apply (enforce with -f)

Refresh 0001-Make-player-examples-installable.patch against gst-examples
1.28.1 so the gtk-play hunk matches the current dependency list, which
now includes gmodule_dep.

Fixes: 843ac09e88a2 ("gst/gstreamer: Bump 1.26.6 -> 1.28.1")
Signed-off-by: Ernest Van Hoecke <ernest.vanhoecke@toradex.com>