cairo: Return back packageconfigs for 1.16.0
The master branch of meta-freescale is compatible with multiply Yocto releases since Kirstone.

Before Scarthgap cairo needs to be compiled with egl/gles. Return
back replacing GL libraries for cairo 1.16.0 to fix rhe building
issue [1].

[1]
2024-01-13 03:04:58 - INFO     - | cairo/1.16.0/recipe-sysroot-native/usr/bin/aarch64-lms-linux/../../libexec/aarch64-lms-linux/gcc/aarch64-lms-linux/13.2.0/ld: ../../boilerplate/.libs/libcairoboilerplate.a(cairo-boilerplate-glx.o): in function `_cairo_boilerplate_gl_cleanup':
2024-01-13 03:04:58 - INFO     - | cairo/1.16.0-r0/boilerplate/cairo-boilerplate-glx.c:60:(.text+0x16c): undefined reference to `glXDestroyContext'
2024-01-13 03:04:58 - INFO     - | cairo/1.16.0/recipe-sysroot-native/usr/bin/aarch64-lms-linux/../../libexec/aarch64-lms-linux/gcc/aarch64-lms-linux/13.2.0/ld: ../../boilerplate/.libs/libcairoboilerplate.a(cairo-boilerplate-glx.o): in function `_cairo_boilerplate_gl_create_surface':
2024-01-13 03:04:58 - INFO     - | cairo/1.16.0-r0/boilerplate/cairo-boilerplate-glx.c:123:(.text+0x288): undefined reference to `glXChooseVisual'
...
2024-01-13 03:04:58 - INFO     - | collect2: error: ld returned 1 exit status

Fixes: 0e478bde ("cairo: Drop the removed packageconfigs")
Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>