imx-uboot-mxs-bootpart.wks.in: drop extra 'rootfs'
${IMAGE_LINK_NAME} already contains "rootfs" at the end, therefore it does not
need to be added explicitly. Otherwise the wic creation fails with:

	wic.filemap.Error: cannot open image file '.../build/tmp-glibc/deploy/images/imx233-olinuxino-maxi/core-image-minimal-imx233-olinuxino-maxi.rootfs.rootfs.uboot-mxsboot-sdcard'

Signed-off-by: Trevor Woerner <twoerner@gmail.com>