xserver-xorg: disable glamor
oe-core enables glamour by default since commit 33864ddc. I tried to build
xserver with glamor but failed first with

|  #error "Platform not recognized"

This could be fixed by

CFLAGS_append_imxgpu2d = " \
    -DLINUX \
"

but then I got

| <sysroot>/usr/include/X11/Xlib.h:222:2: error: conflicting types for 'GC'
|  *GC;
|   ^~
| In file included from ../../xorg-server-1.19.1/glamor/glamor.h:34:0,
|                  from ../../xorg-server-1.19.1/glamor/glamor_priv.h:32,
|                  from ../../xorg-server-1.19.1/glamor/glamor_render.c:35:
| ../../xorg-server-1.19.1/include/gcstruct.h:289:3: note: previous declaration of 'GC' was here
|  } GC;
|    ^~
| make[1]: *** [Makefile:730: glamor_gradient.lo] Error 1

As this needs deeper investigation to fix and we have no experience on how
glamor performs on vivante, disable it for now.

Signed-off-by: Andreas Müller <schnitzeltony@googlemail.com>
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>