ls1021aqds.conf: add the missing quotation mark
Fix following parse error:
ERROR: Unable to parse conf/bitbake.conf: ParseError at /home/jenkins/poky/
meta-fsl-arm/conf/machine/ls1021aqds.conf:16: unparsed line: 'UBOOT_CONFIG[lpuart]
= "ls1021aqds_lpuart_config'

Signed-off-by: Zhenhua Luo <zhenhua.luo@freescale.com>
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>