imx-vpu-hantro: fix build with gcc 15
Change from deprecated K&R function declaration and definitions
to ANSI C style.

GCC 15 by default no longer accepts it:
| decoder_sw/software/test/common/md5_sink.c:68:3: error: too many
| arguments to function 'MD5Init'; expected 0, have 1
|   68 |   MD5Init(&inst->ctx);

With C23 bool, true and false are built in keywords and cannot be
redefined.

Fixes build error:
| ../inc/basetype.h:71:9: error: cannot use keyword 'false' as enumeration constant
|    71 |         false   = 0,

Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>