gstreamer1.0-plugins-good_1.22.5.imx: fix compile time error
GCC-14 set more warnings to errors, demote implicit-function-declaration
and implicit-function-declaration to a warning.
Fixes:
.../v4l2/gstv4l2videoenc.c:782:9: error: implicit declaration of function 'gst_is_dmabuf_memory'; did you mean 'gst_is_v4l2_memory'? [-Wimplicit-function-declaration]
.../sys/v4l2/gstv4l2videodec.c:1185:30: error: initialization of 'GstVideoFrame *' {aka 'struct _GstVideoFrame *'} from incompatible pointer type 'GstVideoCodecFrame *' {aka 'struct _GstVideoCodecFrame *'} [-Wincompatible-pointer-types]
.../sys/v4l2/gstv4l2videodec.c:1187:48: error: passing argument 2 of 'gst_video_decoder_drop_frame' from incompatible pointer type [-Wincompatible-pointer-types]
.../sys/v4l2/gstv4l2videodec.c:1232:30: error: initialization of 'GstVideoFrame *' {aka 'struct _GstVideoFrame *'} from incompatible pointer type 'GstVideoCodecFrame *' {aka 'struct _GstVideoCodecFrame *'} [-Wincompatible-pointer-types]
.../sys/v4l2/gstv4l2videodec.c:1234:48: error: passing argument 2 of 'gst_video_decoder_drop_frame' from incompatible pointer type [-Wincompatible-pointer-types]

Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>
(cherry picked from commit d6c982648868009ea38b36e1eabadef94742b3ca)