imx-base.inc: fix WKS_FILE_DEPENDS's override
Using 'aarch64', as if the WKS_FILE_DEPENDS was conditioned to the
userspace's architecture, will not include imx-boot in a multilib context
(e.g., for a 32-bit userspace). This happens because 'aarch64' will not
be listed in OVERRIDES, and the error below will come up during do_image_wic
task:

wic.filemap.Error: cannot open image file
'.../build/tmp-glibc/deploy/images/microej-imx93/imx-boot':
[Errno 2] No such file or directory

Replace 'aarch64' by mx*-generic-bsp, for both imx8 and imx9, as these
two are aarch64 platforms.

Signed-off-by: Joao Marcos Costa <joaomarcos.costa@bootlin.com>