imx-atf: fix patch applying
Correct the name of patch and prepend FILESEXTRAPATHS, in order to fix
the following issue:

ERROR: imx-atf-2.4+gitAUTOINC+05f788b9bb-r0 do_fetch: Bitbake Fetcher
Error: FetchError('Unable to fetch URL from any source.',
'file://0001-alsa-state-Remove-PCM-devices-mapped-by-5.15-kernel.patch')

Signed-off-by: Thomas Perrot <thomas.perrot@bootlin.com>
(cherry picked from commit f9b9c7e0f8ed074ac9f844c5c1c30fe990504e16)