[hack] jailhouse-imx: utilize installed to native sysroot orphan files with -dev package
Due to an uninvestigated bug in OE, there are some files installed to
recipe's native sysroot during the regular installation process.
Utilize them with a development package as a workaround to fix the
build error [1].

TODO: The root cause of the issue should be investigated and fixed.

[1]
ERROR: jailhouse-imx-git-r0 do_package: QA Issue: jailhouse-imx: Files/directories were installed but not shipped in any package:
...
  .../jailhouse-imx/git/recipe-sysroot-native/usr/lib/python3.11/site-packages/pyjailhouse/extendedenum.py
  .../jailhouse-imx/git/recipe-sysroot-native/usr/lib/python3.11/site-packages/pyjailhouse/config_parser.py
  .../jailhouse-imx/git/recipe-sysroot-native/usr/lib/python3.11/site-packages/pyjailhouse/pci_defs.py
  .../jailhouse-imx/git/recipe-sysroot-native/usr/lib/python3.11/site-packages/pyjailhouse/cell.py
  .../jailhouse-imx/git/recipe-sysroot-native/usr/lib/python3.11/site-packages/pyjailhouse/__init__.py
  .../jailhouse-imx/git/recipe-sysroot-native/usr/lib/python3.11/site-packages/pyjailhouse/sysfs_parser.py
...
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
jailhouse-imx: 38 installed and not shipped files. [installed-vs-shipped]
ERROR: jailhouse-imx-git-r0 do_package: Fatal QA errors were found, failing task.
ERROR: Logfile of failure stored in: tmp/work/imx8mq_lpddr4_wevk-fslc-linux/jailhouse-imx/git/temp/log.do_package.9768
ERROR: Task (recipes-extended/jailhouse/jailhouse-imx_git.bb:do_package) failed with exit code '1'

Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>