qtbase: Define empty PACKAGECONFIG_VULKAN
In cases where non imxgpu and non-fsl SOCs are target do_configure results in

ERROR: qtbase-5.15.0+gitAUTOINC+f6fe4bbab7-r0 do_configure: QA Issue: qtbase: in
valid PACKAGECONFIG: ${@bb.utils.contains('DISTRO_FEATURES', [invalid-packagecon
fig]

Therefore having empty value helps in avoiding this case

Signed-off-by: Khem Raj <raj.khem@gmail.com>