skmm-ep: fix the build error caused by duplicated definition
Remove the duplicated definition to fix the following build errors:
| apps/skmm/lib/skmm_sram.c:42:18: error: redefinition of 'pa_to_va'
| apps/skmm/lib/skmm_sram.c:51:20: error: redefinition of 'va_to_pa'

Signed-off-by: Zhenhua Luo <zhenhua.luo@nxp.com>
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>