imx-atf: Suppress array-bounds error
The array-bounds error is triggered now in cases where it was silent before,
causing errors like:

```
plat/imx/imx8m/hab.c: In function 'imx_hab_handler':
plat/imx/imx8m/hab.c:64:57: error: array subscript 0 is outside array bounds of 'uint32_t[0]' {aka 'unsigned int[]'} [-Werror=array-bounds]
   64 | #define HAB_RVT_CHECK_TARGET_ARM64      ((unsigned long)*(uint32_t *)(HAB_RVT_BASE + 0x18))
      |                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

It appears that these new cases will be silenced soon in gcc [1], so for
now just silence the warning locally as workaround.

[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99578#c39

Fixes: #1084
Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>
(cherry picked from commit dc3cb910f49fc50de9539902b4ecef159603b426)