linux-fslc: Fix TMPDIR build failure
The build failures:

ERROR: linux-fslc-6.6.36+git-r0 do_package_qa: QA Issue: File
/usr/src/debug/linux-fslc/6.6.36+git/lib/oid_registry_data.c in package linux-fslc-src contains reference to TMPDIR [buildpaths]
ERROR: linux-fslc-6.6.36+git-r0 do_package_qa: Fatal QA errors were found, failing task.

ERROR: linux-fslc-6.6.36+git-r0 do_package_qa: QA Issue: File
/usr/src/debug/linux-fslc/6.6.36+git/drivers/tty/vt/consolemap_deftbl.c in package linux-fslc-src contains reference to TMPDIR
ERROR: linux-fslc-6.6.36+git-r0 do_package_qa: Fatal QA errors were found, failing task.

ERROR: linux-fslc-6.6.36+git-r0 do_package_qa: QA Issue: File
/usr/src/debug/linux-fslc/6.6.36+git/drivers/video/logo/logo_linux_clut224.c in package linux-fslc-src contains reference to TMPDIR [buildpaths]
ERROR: linux-fslc-6.6.36+git-r0 do_package_qa: Fatal QA errors were found, failing task

The relevant changes:

 8f24666d05968 tty: vt: conmakehash: cope with abs_srctree no longer in env
 7ea30dacfb713 lib/build_OID_registry: don't mention the full path of the script in output
 0f806d7395704 video: logo: Drop full path of the input filename in generated fil

Signed-off-by: Daiane Angolini <daiane.angolini@foundries.io>
(cherry picked from commit db123d16409e4d3d9b01ce932f307b948565a1a5)