usdpaa-apps: use in6_* macros from glibc instead of kernel
Both glibc and the kernel have in6_* macros definition. Use the one from glibc.
Kernel headers will check for previous libc definitions by including
include/linux/libc-compat.h.

Fix the below build error:
|  [CC] xfrm_km.c                           (bin:srio_ipsec_offload)
| In file included from .../tmp/sysroots/b4860qds-64b/usr/include/linux/xfrm.h:4:0,
|                  from src/srio_ipsec_offload/xfrm_km.c:46:
| .../usr/include/netinet/in.h:99:5: error: expected identifier before numeric constant
|      IPPROTO_HOPOPTS = 0,   /* IPv6 Hop-by-Hop options.  */
|      ^
| In file included from .../tmp/sysroots/b4860qds-64b/usr/include/netinet/ip.h:24:0,
|                  from src/srio_ipsec_offload/xfrm_km.c:52:
| .../tmp/sysroots/b4860qds-64b/usr/include/netinet/in.h:209:8: error: redefinition of 'struct in6_addr'
|  struct in6_addr
|         ^
| In file included from .../tmp/sysroots/b4860qds-64b/usr/include/linux/xfrm.h:4:0,
|                  from src/srio_ipsec_offload/xfrm_km.c:46:
| .../tmp/sysroots/b4860qds-64b/usr/include/linux/in6.h:32:8: note: originally defined here
|  struct in6_addr {
|         ^

Signed-off-by: Ting Liu <ting.liu@freescale.com>
Signed-off-by: Zhenhua Luo <zhenhua.luo@nxp.com>
Acked-by: Otavio Salvador <otavio@ossystems.com.br>