mesa: For i.MX parts without GPU use default gallium and dri
For NXP BSP, building graphics software for a part without GPU can fail with a
dependency issue:

```
ERROR: Nothing RPROVIDES 'libgl' (but /home/r60874/gatesgarth/sources/poky/meta/recipes-gnome/gtk+/gtk+3_3.24.22.bb, /home/r60874/gatesgarth/sources/poky/meta/recipes-graphics/cogl/cogl-1.0_1.22.8.bb RDEPENDS on or otherwise requires it)
```

This is fixed by adding a third case configuration using the default gallium and dri.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>
(cherry picked from commit 148581622b1097123f0fdb905c3167d0d6d6f5b7)