u-boot-qoriq: Fix python function for fsl-lsch2-32b arch
Add missing argument in function getVar() to avoid error:

Exception: TypeError: getVar() missing 1 required positional argument: 'expand'

Signed-off-by: Fabio Berton <fabio.berton@ossystems.com.br>
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>