imx-vpuwrap: fix build error
Add missing include file. Otherwise with latest master we see:
| ../git/vpu_wrapper_hantro_encoder.c:953:3: error: implicit declaration of function 'gettimeofday' [-Wimplicit-function-declaration]
|   953 |   gettimeofday (&pObj->tvEnd, NULL);

Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>