qt4-imx-support: fix build for imxgpu2d SOCs
Before this change, when imxgpu2d is selected, the qt4 do_configure
fails with the following error:

| EGL (EGL/egl.h) auto-detection... ()
| compiling egl.cpp
...
| /home/wrk/yocto/build-qt4/tmp/work/imx8mmevk-fslc-linux/qt4-embedded/4.8.7-r0/recipe-sysroot/usr/include/EGL/eglplatform.h:150:10: fatal error: X11/Xlib.h: No such file or directory
|   150 | #include <X11/Xlib.h>
|       |          ^~~~~~~~~~~~
| compilation terminated.
| Makefile:178: recipe for target 'egl.o' failed
| make: *** [egl.o] Error 1
| EGL (EGL/egl.h) disabled.
| EGL (GLES/egl.h) auto-detection... ()
...
| /home/wrk/yocto/build-qt4/tmp/work/imx8mmevk-fslc-linux/qt4-embedded/4.8.7-r0/recipe-sysroot/usr/include/EGL/eglplatform.h:150:10: fatal error: X11/Xlib.h: No such file or directory
|   150 | #include <X11/Xlib.h>
|       |          ^~~~~~~~~~~~
| compilation terminated.
| Makefile:178: recipe for target 'egl4gles1.o' failed
| make: *** [egl4gles1.o] Error 1
| EGL (GLES/egl.h) disabled.
| The EGL functionality test failed!

This is because the -DLINUX=1 and -DEGL_API_FB=1 flags added to QT_CONFIG_FLAGS
are not pushed down during these configuration tests.

This commit adds these two flags directly to the related .pro files
in Qt4 sources.

Since it's been a long time that meta-qt4 is not updated anymore,
the patch can be backported to LTS releases.

Signed-off-by: Mauro Salvini <m.salvini@koansoftware.com>
(cherry picked from commit 4aed4a58335af8e96815124f17f47060d1053c48)