u-boot-qoriq: fix bug with gcc10
Newer buildhost distributions as Fedora 32 come with GCC10+, which causes:
	gcc  -isystemtmp/work/lx2160acex7-poky-linux/u-boot-qoriq/2019.10+fslgit-r0/recipe-sysroot-native/usr/include -O2 -pipe -Ltmp/work/lx2160acex7-poky-linux/u-boot-qoriq/2019.10+fslgit-r0/recipe-sysroot-native/usr/lib                         -Ltmp/work/lx2160acex7-poky-linux/u-boot-qoriq/2019.10+fslgit-r0/recipe-sysroot-native/lib                         -Wl,--enable-new-dtags                         -Wl,-rpath-link,tmp/work/lx2160acex7-poky-linux/u-boot-qoriq/2019.10+fslgit-r0/recipe-sysroot-native/usr/lib                         -Wl,-rpath-link,tmp/work/lx2160acex7-poky-linux/u-boot-qoriq/2019.10+fslgit-r0/recipe-sysroot-native/lib                         -Wl,-rpath,tmp/work/lx2160acex7-poky-linux/u-boot-qoriq/2019.10+fslgit-r0/recipe-sysroot-native/usr/lib                         -Wl,-rpath,tmp/work/lx2160acex7-poky-linux/u-boot-qoriq/2019.10+fslgit-r0/recipe-sysroot-native/lib                         -Wl,-O1 -Wl,--allow-shlib-undefined -Wl,--dynamic-linker=tmp/sysroots-uninative/x86_64-linux/lib/ld-linux-x86-64.so.2  -o scripts/dtc/dtc scripts/dtc/dtc.o scripts/dtc/flattree.o scripts/dtc/fstree.o scripts/dtc/data.o scripts/dtc/livetree.o scripts/dtc/treesource.o scripts/dtc/srcpos.o scripts/dtc/checks.o scripts/dtc/util.o scripts/dtc/dtc-lexer.lex.o scripts/dtc/dtc-parser.tab.o
	tmp/hosttools/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here
	collect2: error: ld returned 1 exit status
	make[3]: *** [scripts/Makefile.host:106: scripts/dtc/dtc] Error 1
	make[2]: *** [tmp/work/lx2160acex7-poky-linux/u-boot-qoriq/2019.10+fslgit-r0/git/scripts/Makefile.build:432: scripts/dtc] Error 2
	make[1]: *** [tmp/work/lx2160acex7-poky-linux/u-boot-qoriq/2019.10+fslgit-r0/git/Makefile:528: scripts] Error 2
	make[1]: Leaving directory 'tmp/work/lx2160acex7-poky-linux/u-boot-qoriq/2019.10+fslgit-r0/build/mdr_gt_tfa_defconfig

'Backporting' fix from mainline to this failure.

Signed-off-by: Jens Rehsack <sno@netbsd.org>