gst1.0-fsl-plugin: add STAGING_KERNEL_BUILDDIR to the include dirs list
The new version of the gst1.0-fsl-plugin package uses the preprocessor
to do conditional compilation:

#if LINUX_VERSION_CODE < KERNEL_VERSION(4, 1, 0)

And to use those macros it includes 'linux/version.h' header file.

This is failing because it is including the 'linux/version.h' file from
the sysroot, which comes from the 'linux-libc-headers' recipe used to
build the toolchain, instead of the real kernel version we are building
and running later on.

Otherwise the build fails with:

error: 'VIDIOC_S_INPUT_CROP' undeclared

Signed-off-by: Javier Viguera <javier.viguera@digi.com>
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>