imx-gpu-viv: Limit dependency on kernel-module-imx-gpu-viv
Building core-image-weston with multilib support and builtin graphics
fails:

```
ERROR: Trying to resolve runtime dependency kernel-module-imx-gpu-viv resulted in conflicting PREFERRED_PROVIDER entries being found.
The providers found were: ['virtual:multilib:lib32:/opt/work/upstream/sources/meta-freescale/recipes-kernel/linux/linux-imx-mfgtool_5.10.bb', '/opt/work/upstream/sources/meta-freescale/recipes-kernel/linux/linux-imx-mfgtool_5.10.bb']
The PREFERRED_PROVIDER entries resulting in this conflict were: ['PREFERRED_PROVIDER_lib32-linux-imx-mfgtool = lib32-linux-imx-mfgtool', 'PREFERRED_PROVIDER_linux-imx-mfgtool = linux-imx-mfgtool']. You could set PREFERRED_RPROVIDER_kernel-module-imx-gpu-viv
ERROR: Required build target 'core-image-weston' has no buildable providers.
Missing or unbuildable dependency chain was: ['core-image-weston', 'matchbox-terminal', 'gtk+3', 'virtual/egl', 'kernel-module-imx-gpu-viv']
```

This is the configuration added in local.conf:

```
require conf/multilib.conf
MULTILIBS = "multilib:lib32"
DEFAULTTUNE:virtclass-multilib-lib32 = "armv7athf-neon"
IMAGE_INSTALL:append = " lib32-glibc lib32-libgcc lib32-libstdc++"
MACHINE_USES_VIVANTE_KERNEL_DRIVER_MODULE = "0"
```

The error is confusing since it refers to _module_ graphics and to
linux-imx-mfgtool, neither of which are relevant to the build.

Rework the implementation so that the module graphics are recommended
only when configured and the logic marking the kernel as a provider of
module graphics can be dropped. Also, move the dependency to the
machine level to avoid making imx-gpu-viv machine-specific.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>