mesa: Limit OSMesa to DRM and remove swrast
OSMesa was originally added for i.MX 8 only. This limitation was recently dropped
accidentally. Additionally, the 8DualXLite has no GPU and fails to build:

```
| In file included from ../../../mesa-demos-8.4.0/src/osdemos/osdemo32.c:14:
| ../../../mesa-demos-8.4.0/src/util/glut_wrap.h:9:12: fatal error: GL/glut.h: No such file or directory
|     9 | #  include <GL/glut.h>
|       |            ^~~~~~~~~~~
| compilation terminated.
```

Fix the OSMesa configuration by limiting it to parts with DRM.

Also, adding swrast prevents the use of hardware acceleration. Drop swrast.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>