bluealsa: move bbappend to dynamic-layers to avoid parsing errors
The bluealsa recipe already exists in the meta-multimedia layer from the
meta-openembedded repository. When meta-multimedia is not included in the
configuration, the bbappend file triggers a parsing error:

        ERROR: No recipes in default available for:
        meta-freescale/recipes-multimedia/bluealsa/bluealsa_%.bbappend

To prevent this issue and ensure the bbappend is applied only when the
appropriate layer is present, the file has been moved to dynamic-layers.

Signed-off-by: Benjamin Missey <benjamin.missey@non.se.com>