mxldr: Fix QA errors seen on x86 builds
* Respect OE flags inside makefiles
* Its not a autotooled recipe but a simple makefile based one

Fixes
NOTE: i586-yoe-linux-musl-objdump -p
TOPDIR/build/tmp/work/i586-yoe-linux-musl/mxsldr/0.0.0+gitAUTOINC+c40d804725-r0/packages-split/mxsldr/usr/bin/mxsldr
ERROR: QA Issue: No GNU_HASH in the elf binary:
'TOPDIR/build/tmp/work/i586-yoe-linux-musl/mxsldr/0.0.0+gitAUTOINC+c40d804725-r0/packages-split/mxsldr/usr/bin/mxsldr'
[ldflags]

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>
(cherry picked from commit 9ae826a5ddb318e7f9248cbab426a509c69f1e19)