imx-seco-libs: Fix installs with usrmerge distro feature
Fixes QA errors like
ERROR: imx-seco-libs-git-r0 do_package: QA Issue: imx-seco-libs: Files/directories were installed but not shipped in any package:
  /usr/usr
  /usr/usr/lib
  /usr/usr/lib/hsm_lib.a
  /usr/usr/lib/she_lib.a
  /usr/usr/lib/seco_nvm_manager.a

Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit b24ea69e457571d1f924c8a801de456f9680b1ff)