fsl-eula-unpack.bbclass: Unpack NXP EULA archives last
NXP EULA archive-based builds like imx-gpu-viv fail because the unpacked
folder is empty:

```
ERROR: imx-gpu-viv-1_6.4.3.p2.4-aarch64-r0 do_populate_lic: QA Issue: imx-gpu-viv: LIC_FILES_CHKSUM points to an invalid file: /opt/work/upstream/fsl-xwayland/tmp/work/cortexa53-crypto-mx8m-fsl-linux/imx-gpu-viv/1_6.4.3.p2.4-aarch64-r0/imx-gpu-viv-6.4.3.p2.4-aarch64/COPYING [license-checksum]
```

This is traced to a change in bitbake:

```
b074f4a ast: Improve function flags handling for EXPORT_FUNCTIONS
```

That change includes a fix for cleandirs, so now the call to base_unpack,
done after the NXP EULA archive unpack, does now remove the folder(s)
created by the NXP EULA archive unpack.

Fix the problem by simply unpacking the NXP EULA archives last.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>