imx-gpu-viv: Mark libvulkan-imx unavailable for 8M Mini
The GPU drivers do not support 8M Mini, so properly exclude them from
PACKAGES so the user gets an earlier indication of a problem:

```
$ bitbake vulkan-loader
ERROR: Nothing RPROVIDES 'libvulkan-imx' (but /.../poky/meta/recipes-graphics/vulkan/vulkan-loader_1.3.216.0.bb RDEPENDS on or otherwise requires it)
ERROR: Required build target 'vulkan-loader' has no buildable providers.
Missing or unbuildable dependency chain was: ['vulkan-loader', 'libvulkan-imx']
```

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>
(cherry picked from commit ee92b5a8b2cad45de267d3cf6dae9251f5ed11fd)