gstreamer1.0-plugins-base_1.22.5.imx: fix compile time error
GCC-14 set more warnings to errors, demote implicit-function-declaration to a warning.
Fixes:

| .../gst-libs/gst/gl/gstglphymemory.c:312:25: error: assignment to 'GDestroyNotify' {aka 'void (*)(void *)'} from incompatible pointer type 'void (*)(GstMemory *)' {aka 'void (*)(struct _GstMemory *)'} [-Wincompatible-pointer-types]
| .../gst-libs/gst/gl/gstglphymemory.c:345:7: error: passing argument 2 of 'gst_gl_context_thread_add' from incompatible pointer type [-Wincompatible-pointer-types]
| .../gst-libs/gst/gl/gstglphymemory.c:360:9: error: assignment to 'GstGLBaseMemory *' {aka 'struct _GstGLBaseMemory *'} from incompatible pointer type 'GstMemory *' {aka 'struct _GstMemory *'} [-Wincompatible-pointer-types]
| .../git/gst-libs/gst/gl/gstglupload.c:2154:51: error: passing argument 6 of 'directviv->TexDirectVIVMap' from incompatible pointer type [-Wincompatible-pointer-types]

Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>
(cherry picked from commit a7a573a216d5a1ee3ac0349c886d454773a36627)