gstreamer1.0-plugins-base: Provide gstreamer1.0-plugins-base-videoconvertscale
This builds a bridge for packagegroups from oe-core master which are
upgraded to use gstreamer 1.22 and some packages are merged together
e.g. videoconvertscale is unified version of videoconvert and videoscale
packages

Fixes
ERROR: gstreamer1.0-meta-base-1.0-r0 do_package_qa: QA Issue: gstreamer1.0-meta-base rdepends on gstreamer1.0-plugins-base-videoconvertscale, but it isn't a build dependen
cy? [build-deps]

Signed-off-by: Khem Raj <raj.khem@gmail.com>