optee-client-qoriq: GCC 8 format-truncation error
*Fix the below error:
|libteec/src/teec_trace.c:110:24: error: '%s' directive output may be truncated
|writing up to 255 bytes into a region of size 246 [-Werror=format-truncation=]

Signed-off-by: Chunrong Guo <chunrong.guo@nxp.com>
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>
(cherry picked from commit 0368b34d0d593de5d6e3a8770d5c80e4ed43c1ab)