imx-alsa-plugins: update to commit cde60d6
With the change to linux-imx-headers 4.19.35 the build of imx-alsa-plugins
fails. Likely "linux/mxc_asrc.h" would require an include.
In the latest sources this is done in the source file which includes it.

| /workdir/oe/tmp/work/aarch64-mx8-tdx-linux/imx-alsa-plugins/1.0.26-r0/recipe-sysroot/usr/include/imx/linux/mxc_asrc.h:125:2: error: unknown type name 'snd_pcm_format_t'
|   125 |  snd_pcm_format_t input_format;
ff.

From the imx-alsa-plugins commit:
    Include latest asrc_pair change for k4.14 build [YOCIMX-3558]

    asrc_pair: update according to latest mxc_asrc.h

    The mxc_asrc.h is updated for supporting new module on 815.
    The main change is the xxx_word_width is replaced by xxx_format.

    As we've switched to use git fork build, change recipe PV to 'git'.
    Will upstream this recipe to community later.

    Signed-off-by: Yuqing Zhu <carol.zhu@nxp.com>

Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>