Revert "imx-lib: Fix GCC 15 build errors"
When building imx93-11x11-lpddr4x-evk against yocto
walnascar 5.2.2 (GCC 14) this fix causes error:

| mxc_hdmi-cec.c:76:8: error: unknown type name 'bool'
|    76 | static bool cec_init_flag = false;
|       |        ^~~~

This reverts commit 74c4045f275601f2e7b58cf0c55acc87c369e5d2.

Signed-off-by: Mikko Gronoff <mikko.gronoff@qt.io>