imx6sxsabreauto: Switch virtual/bootloader to u-boot-fslc
The virtual/bootloader for this board used to be u-boot-imx which does
not include the board in COMPATIBLE_MACHINE any more, so the choice is
migrate to u-boot-fslc.

The error message:
   ERROR: Nothing PROVIDES 'virtual/bootloader' (but /media/daiane/TRIFORCE/yocto/dunfell/sources/poky/meta/recipes-core/images/core-image-minimal.bb DEPENDS on or otherwise requires it)
   u-boot-imx PROVIDES virtual/bootloader but was skipped: incompatible with machine imx6sxsabreauto (not in COMPATIBLE_MACHINE)

Signed-off-by: Daiane Angolini <daiane.angolini@nxp.com>