imx8mm-evk.inc: Drop qca9377
The build for kernel-module-qca9377 is broken:

```
| /.../yocto/master/build/tmp/work/imx8mm_lpddr4_evk-fsl-linux/kernel-module-qca9377/3.1-r0/git/CORE/SERVICES/COMMON/adf/linux/adf_os_dma_pvt.h:104:25: error: 'DMA_ATTR_NON_CONSISTENT' undeclared (first use in this function)
|   104 |                         DMA_ATTR_NON_CONSISTENT);
|       |                         ^~~~~~~~~~~~~~~~~~~~~~~
```

The Linux API here is changed for 5.10, so the i.MX fork is now
incompatible. Nothing suitable is found in Qualcomm's source either,
so drop qca9377.

Fixes: #851
Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>