Revert "linux-qoriq recipes: reorder merge_delta_config task"
This reverts commit 6e0b6f295fa7f62484b7a448fb729fbd32191a6b,
which unfortunately causes a blank build for e.g. ls2088ardb fail as that

    ERROR: linux-qoriq-4.19-r0 do_preconfigure: Execution of 'mp/work/ls2088ardb-poky-linux/linux-qoriq/4.19-r0/temp/run.do_preconfigure.13614' failed with exit code 2:
    tmp/work/ls2088ardb-poky-linux/linux-qoriq/4.19-r0/temp/run.do_preconfigure.13614: 119: tmp/work/ls2088ardb-poky-linux/linux-qoriq/4.19-r0/temp/run.do_preconfigure.13614: cannot open tmp/work/ls2088ardb-poky-linux/linux-qoriq/4.19-r0/defconfig: No such file
    WARNING: exit code 2 from a shell command.

    ERROR: Logfile of failure stored in: tmp/work/ls2088ardb-poky-linux/linux-qoriq/4.19-r0/temp/log.do_preconfigure.13614
    Log data follows:
    | DEBUG: Executing shell function do_preconfigure
    | tmp/work/ls2088ardb-poky-linux/linux-qoriq/4.19-r0/temp/run.do_preconfigure.13614: 119: tmp/work/ls2088ardb-poky-linux/linux-qoriq/4.19-r0/temp/run.do_preconfigure.13614: cannot open tmp/work/ls2088ardb-poky-linux/linux-qoriq/4.19-r0/defconfig: No such file
    | WARNING: exit code 2 from a shell command.
    | ERROR: Execution of 'tmp/work/ls2088ardb-poky-linux/linux-qoriq/4.19-r0/temp/run.do_preconfigure.13614' failed with exit code 2:
    | tmp/work/ls2088ardb-poky-linux/linux-qoriq/4.19-r0/temp/run.do_preconfigure.13614: 119: tmp/work/ls2088ardb-poky-linux/linux-qoriq/4.19-r0/temp/run.do_preconfigure.13614: cannot open tmp/work/ls2088ardb-poky-linux/linux-qoriq/4.19-r0/defconfig: No such file
    | WARNING: exit code 2 from a shell command.
    |
    ERROR: Task (/build/sno/sources/meta-freescale/recipes-kernel/linux/linux-qoriq_4.19.bb:do_preconfigure) failed with exit code '1'

This is caused by do_preconfigure() from classes/fsl-kernel-localversion.bbclass
expects a ${WORKDIR}/defconfig which was earlier created by merge_delta_config.

Signed-off-by: Jens Rehsack <sno@netbsd.org>