kernel-module-isp-vvcam: fix LIC_FILES_CHKSUM when using devtool
This recipe fails when using devtool:

  ERROR: [...] do_populate_lic: QA Issue: kernel-module-isp-vvcam: LIC_FILES_CHKSUM points to an invalid file: [...]/build/tmp/work/nitrogen8mp-fslc-linux/kernel-module-isp-vvcam/4.2.2.16.0-r0/git/vvcam/LICENSE [license-checksum]

How to reproduce:

  devtool modify kernel-module-isp-vvcam
  bitbake kernel-module-isp-vvcam

Fix by pointing to a path relative to S.

Signed-off-by: Luca Ceresoli <luca.ceresoli@bootlin.com>
(cherry picked from commit c1cb76721b333c3b5f1ee8f9e5e84a4fad8b1bf1)