imx-opencl-converter: fix compile time error
GCC-14 set more warnings to errors, fix the code.

Fixes:
| .../src/ocl.c:258: 22: error: passing argument 6 of 'clGetProgramBuildInfo' from incompatible pointer type [-Wincompatible-pointer-types]

Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>
(cherry picked from commit e836f27b1cf3bee0ac23360428b17a4c10c6f414)