ceetm: use new api tc_print_rate from iproute2
Fix the build issue due to api change in iproute2:
| dpaa1_ceetm.c:637:4: error: too few arguments to function 'print_rate'
| print_rate(buf, sizeof(buf), qopt->rate);
| ^~~~~~~~~~

Signed-off-by: Ting Liu <ting.liu@nxp.com>