imx6qdlsabre*.conf: Fix UBOOT_CONFIG override for u-boot-imx-mfgtool
Building u-boot-imx-mfgtool for i.MX 6 SABRE results in the following
error:
```
ERROR: Nothing PROVIDES 'u-boot-imx-mfgtool'
u-boot-imx-mfgtool was skipped: The selected UBOOT_CONFIG key ['mfgtool'] has no match in dict_keys(['sd-fslc', 'sd-imx', 'sd-optee-imx', 'sata-imx', 'mfgtool-imx']).
```

The UBOOT_CONFIG key for u-boot-imx-mfgtool is set as `mfgtool`, but the
configuration for NXP BSP uses `mfgtool-imx` because there is not
alignment between u-boot-imx and mainline on the machine to use for
i.MX 6 SABRE boards.

Changing the selected key to mfgtool-imx is difficult, so rework the
original solution so the selection of the machine name is done in a
separate variable and the keys can be kept simple without the `-imx`
adornment.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>
(cherry picked from commit d9148f97bc86264d633aa03731fd9ab16bed40c0)