weston: Append EGL_CFLAGS to CFLAGS for imxgpu2d
When building weston for imxgpu2d machine, CFLAGS doesn't get
EGL_CFLAGS value and cause the error bellow:

| ../build/tmp/sysroots/imx6sl-warp/usr/include/EGL/eglvivante.h:266:2: error: #error "Platform not recognized"
|  #error "Platform not recognized"

Signed-off-by: Fabio Berton <fabio.berton@ossystems.com.br>
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>