cs4315-firmware: remove recipe
The source code of cs4315-firmware is not available in public git repo
due to license issue, remove the recipe.

Build error log:
ERROR: Function failed: Fetcher failure for URL: 'git://git.freescale.com/ppc/sdk/firmware.git;nobranch=1'. Unable to fetch URL from any source.

Signed-off-by: Zhenhua Luo <zhenhua.luo@freescale.com>