optee-os: Fix RPMB build break
When CFG_RPMB_FS=y, OP-TEE os no longer compiles because imx_rpmb.c
tries to include a header that doesn't exist. This issue seems linked
to a rework that allows to compile i.MX Secure Non-Volatile Storage
driver without RPMB.

```
|   CC      optee-os/3.15.0.imx-r0/build/core/arch/arm/plat-imx/imx_rpmb.o
| core/arch/arm/plat-imx/imx_rpmb.c:5:10: fatal error: drivers/imx_snvs.h: No such file or directory
|     5 | #include <drivers/imx_snvs.h>
|       |          ^~~~~~~~~~~~~~~~~~~~
| compilation terminated.
| make: *** [mk/compile.mk:159: optee-os/3.15.0.imx-r0/build/core/arch/arm/plat-imx/imx_rpmb.o] Error 1
| make: *** Waiting for unfinished jobs....
|   CC     optee-os/3.15.0.imx-r0/build/core/crypto/crypto.o
|   CC      optee-os/3.15.0.imx-r0/build/core/arch/arm/plat-imx/imx_dt.o
| make: Leaving directory 'optee-os/3.15.0.imx-r0/git'
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
ERROR: Task (optee-imx/optee-os_3.15.0.imx.bb:do_compile) failed with exit code '1'
```

This is fixed in the upcoming release NXP 5.15.5-1.0.0. Backport the
patch.

Fixes: #997
Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>