image_types_fsl.bbclass: fix barebox bootstream generation
Since the image_types.bbclass is not cd'ing to ${DEPLOY_DIR_IMAGE}
anymore, do that in a subshell before generating the boostream.
This fixes the following build failure:

ERROR: Error: The image creation script
   '.../core-image-minimal/1.0-r0/temp/create_image.barebox.mxsboot-sdcard' returned 1:
error: unable to find command file imx-bootlets-barebox_ivt.bd-cfa10058

Change-Id: I5881c6bc333bef42a3f61d07b7bbd6c87c7d45e7
Signed-off-by: Alexandre Belloni <alexandre.belloni@free-electrons.com>