xserver-xorg: Disable glamor for i.MX 8
Like i.MX 6 and 7, need to disable glamor for i.MX 8 to avoid a build break:

In file included from /home/r60874/upstream/fsl-xwayland/tmp/work/aarch64-mx8mm-fsl-linux/xserver-xorg/2_1.20.1-r0/recipe-sysroot/usr/include/EGL/eglplatform.h:179,
                 from /home/r60874/upstream/fsl-xwayland/tmp/work/aarch64-mx8mm-fsl-linux/xserver-xorg/2_1.20.1-r0/recipe-sysroot/usr/include/epoxy/egl_generated.h:11,
                 from /home/r60874/upstream/fsl-xwayland/tmp/work/aarch64-mx8mm-fsl-linux/xserver-xorg/2_1.20.1-r0/recipe-sysroot/usr/include/epoxy/egl.h:46,
                 from ../../xorg-server-1.20.1/glamor/glamor_priv.h:43,
                 from ../../xorg-server-1.20.1/glamor/glamor_composite_glyphs.c:25:
/home/r60874/upstream/fsl-xwayland/tmp/work/aarch64-mx8mm-fsl-linux/xserver-xorg/2_1.20.1-r0/recipe-sysroot/usr/include/EGL/eglvivante.h:267:1: error: conflicting types for 'fbCreateWindow'
 fbCreateWindow(
 ^~~~~~~~~~~~~~
In file included from ../../xorg-server-1.20.1/glamor/glamor.h:36,
                 from ../../xorg-server-1.20.1/glamor/glamor_priv.h:32,
                 from ../../xorg-server-1.20.1/glamor/glamor_composite_glyphs.c:25:
../../xorg-server-1.20.1/fb/fb.h:1115:2: note: previous declaration of 'fbCreateWindow' was here
  fbCreateWindow(WindowPtr pWin);
  ^~~~~~~~~~~~~~

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>