imx-gst1.0-plugin: fix compile time error
GCC-14 set more warnings to errors, demote the ones which trigger to a warning.
Fixes:
| .../tools/grecorder/grecorder.c:161:38: error: initialization of 'pthread_t' {aka 'long unsigned int'} from 'void *' makes integer from pointer without a cast [-Wint-conversion]
| .../tools/grecorder/grecorder.c:162:43: error: initialization of 'pthread_t' {aka 'long unsigned int'} from 'void *' makes integer from pointer without a cast [-Wint-conversion]
| .../tools/grecorder/grecorder.c:845:7: error: passing argument 3 of 'recorder->register_event_handler' from incompatible pointer type [-Wincompatible-pointer-types]
| .../tools/grecorder/grecorder.c:43:39: error: passing argument 3 of 'pthread_create' from incompatible pointer type [-Wincompatible-pointer-types]
| .../tools/grecorder/grecorder.c:71:39: error: passing argument 3 of 'pthread_create' from incompatible pointer type [-Wincompatible-pointer-types]
| .../tools/grecorder/grecorder.c:81:15: error: assignment to 'pthread_t' {aka 'long unsigned int'} from 'void *' makes integer from pointer without a cast [-Wint-conversion]
| .../tools/grecorder/grecorder.c:52:15: error: assignment to 'pthread_t' {aka 'long unsigned int'} from 'void *' makes integer from pointer without a cast [-Wint-conversion]
| .../plugins/beepdec/beepdec.c:54:34: error: initialization of 'void (*)(GstObject *, ...)' {aka 'void (*)(struct _GstObject *, ...)'} from incompatible pointer type 'void (*)(GstAudioDecoder *, GstClockTime)' {aka 'void (*)(struct _GstAudioDecoder *, long unsigned int)'} [-Wincompatible-pointer-types]
| .../plugins/beepdec/beepdec.c:55:36: error: initialization of 'void (*)(GstObject *, ...)' {aka 'void (*)(struct _GstObject *, ...)'} from incompatible pointer type 'void (*)(GstAudioDecoder *, GstClockTime)' {aka 'void (*)(struct _GstAudioDecoder *, long unsigned int)'} [-Wincompatible-pointer-types]
| .../plugins/beepdec/beepdec.c:56:29: error: initialization of 'void (*)(GstObject *, ...)' {aka 'void (*)(struct _GstObject *, ...)'} from incompatible pointer type 'void (*)(GstAudioDecoder *, gboolean)' {aka 'void (*)(struct _GstAudioDecoder *, int) '} [-Wincompatible-pointer-types]
| .../recipe-sysroot/usr/include/gstreamer-1.0/gst/audio/gstaudiodecoder.h:49:4: error: passing argument 2 of 'gstsutils_load_default_property' from incompatible pointer type [-Wincompatible-pointer-types]
| .../plugins/beepdec/beepdec.c:445:24: error: assignment to 'void * (*)(size_t)' {aka 'void * (*)(long unsigned int)'} from incompatible pointer type 'void * (*)(uint32)' {aka 'void * (*)(unsigned int)'} [-Wincompatible-pointer-types]
| .../plugins/beepdec/beepdec.c:510:20: error: assignment to 'void * (*)(size_t)' {aka 'void * (*)(long unsigned int)'} from incompatible pointer type 'void * (*)(uint32)' {aka 'void * (*)(unsigned int)'} [-Wincompatible-pointer-types]
| .../plugins/videoconvert/gstimxvideoconvert.c:1662:24: error: assignment to 'void **' from incompatible pointer type 'guint8 *' {aka 'unsigned char *'} [-Wincompatible-pointer-types]
| .../plugins/videoconvert/gstimxvideoconvert.c:1673:74: error: passing argument 2 of '_set_cached_phyaddr' from incompatible pointer type [-Wincompatible-pointer-types]
| .../plugins/compositor/gstimxcompositor.c:1579:28: error: assignment to 'void **' from incompatible pointer type 'guint8 *' {aka 'unsigned char *'} [-Wincompatible-pointer-types]
| .../plugins/compositor/gstimxcompositor.c:1591:77: error: passing argument 2 of '_set_cached_phyaddr' from incompatible pointer type [-Wincompatible-pointer-types]
| .../plugins/compositor/gstimxcompositor.c:1954:7: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
| .../tools/grecorder/recorder_engine.c:1253:41: error: passing argument 1 of 'strrchr' from incompatible pointer type [-Wincompatible-pointer-types]
| .../tools/grecorder/recorder_engine.c:1901:22: error: assignment to 'GString *' {aka 'struct _GString *'} from incompatible pointer type 'char *' [-Wincompatible-pointer-types]
| .../tools/grecorder/recorder_engine.c:1916:18: error: assignment to 'GString *' {aka 'struct _GString *'} from incompatible pointer type 'char *' [-Wincompatible-pointer-types]
| .../libs/v4l2_core/gstimxv4l2.c:1203:92: error: passing argument 3 of 'gst_imx_v4l2_dequeue_gstbuffer' from incompatible pointer type [-Wincompatible-pointer-types]
| .../plugins/aiurdemux/aiurdemux.c:517:7: error: implicit declaration of function 'aiurdemux_check_stream_status'; did you mean 'aiurdemux_send_stream_eos'? [-Wimplicit-function-declaration]
| .../plugins/aiurdemux/aiurdemux.c:1681:7: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
| .../plugins/aiurdemux/aiurdemux.c:4182:47: error: passing argument 3 of 'IParser->seek' from incompatible pointer type [-Wincompatible-pointer-types]
| .../plugins/aiurdemux/aiurdemux.c:4217:11: error: passing argument 3 of 'IParser->seek' from incompatible pointer type [-Wincompatible-pointer-types]
| .../plugins/aiurdemux/aiurdemux.c:4240:17: error: passing argument 3 of 'IParser->seek' from incompatible pointer type [-Wincompatible-pointer-types]

Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>
(cherry picked from commit 2dd7d0824d56932f090600680f797c4d5eb9c9f8)