gstreamer1.0-python: package the internal libraries explicitly
setuptools3-base FILES assignments have been simplified, therefore the
internal libraries should be now packaged explicitly.

Fixes
ERROR: QA Issue: gstreamer1.0-python: Files/directories were installed but not shipped in any package:
  /usr/lib/gstreamer-1.0/libgstpython.so

Signed-off-by: Khem Raj <raj.khem@gmail.com>