set PREFERRED_PROVIDER_virtual/libx11 to libx11
To avoid the following error when building fsl-image-lsb/fsl-image-lsb-sdk:
ERROR: Multiple .bb files are due to be built which each provide virtual/libx11
(/home/jenkins/poky/meta/recipes-graphics/xorg-lib/libx11_1.3.4.bb
/home/jenkins/poky/meta/recipes-graphics/xorg-lib/libx11-trim_1.3.4.bb).

task-core-lsb requires runtime dependency "libx11-locale" which is only
provided by libx11_1.3.4.bb. Meanwhile, PREFERRED_PROVIDER_virtual/libx11 is
by default set to "libx11-trim". File "libx11-trim_1.3.4.bb" is selected when
adding dependency virtual/libx11 for dbus/qt4 etc.

Both of the two recipes provide virtual/libx11.

Signed-off-by: Ting Liu <b28495@freescale.com>