kernel-module-qca6174_3.0: avoid kernel module build errors
Currently the kernel module fails to build with following
undefined symbols due to missing Kconfig option.

| rpb-dunfell/build-rpb-wayland/tmp-rpb_wayland-glibc/work/imx8mqevk-linaro-linux/kernel-module-qca6174/3.0-r0/git/CORE/HDD/src/wlan_hdd_cfg80211.c:15910:13: error: 'qca_wlan_vendor_ocb_set_config_policy' undeclared here (not in a function); did you mean 'qca_wlan_vendor_setband_policy'?
| 15910 |   .policy = qca_wlan_vendor_ocb_set_config_policy,
|       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |             qca_wlan_vendor_setband_policy
| rpb-dunfell/build-rpb-wayland/tmp-rpb_wayland-glibc/work/imx8mqevk-linaro-linux/kernel-module-qca6174/3.0-r0/git/CORE/HDD/src/wlan_hdd_cfg80211.c:15919:13: error: 'qca_wlan_vendor_ocb_set_utc_time_policy' undeclared here (not in a function); did you mean 'qca_wlan_vendor_ll_set_policy'?
| 15919 |   .policy = qca_wlan_vendor_ocb_set_utc_time_policy,
|       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |             qca_wlan_vendor_ll_set_policy
| rpb-dunfell/build-rpb-wayland/tmp-rpb_wayland-glibc/work/imx8mqevk-linaro-linux/kernel-module-qca6174/3.0-r0/git/CORE/HDD/src/wlan_hdd_cfg80211.c:15929:13: error: 'qca_wlan_vendor_ocb_start_timing_advert_policy' undeclared here (not in a function); did you mean 'qca_wlan_vendor_attr_ocb_start_timing_advert'?
| 15929 |   .policy = qca_wlan_vendor_ocb_start_timing_advert_policy,
|       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |             qca_wlan_vendor_attr_ocb_start_timing_advert
| rpb-dunfell/build-rpb-wayland/tmp-rpb_wayland-glibc/work/imx8mqevk-linaro-linux/kernel-module-qca6174/3.0-r0/git/CORE/HDD/src/wlan_hdd_cfg80211.c:15938:13: error: 'qca_wlan_vendor_ocb_stop_timing_advert_policy' undeclared here (not in a function); did you mean 'qca_wlan_vendor_attr_ocb_stop_timing_advert'?
| 15938 |   .policy = qca_wlan_vendor_ocb_stop_timing_advert_policy,
|       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |             qca_wlan_vendor_attr_ocb_stop_timing_advert
| rpb-dunfell/build-rpb-wayland/tmp-rpb_wayland-glibc/work/imx8mqevk-linaro-linux/kernel-module-qca6174/3.0-r0/git/CORE/HDD/src/wlan_hdd_cfg80211.c:15956:13: error: 'qca_wlan_vendor_dcc_get_stats' undeclared here (not in a function); did you mean 'qca_wlan_vendor_attr_dcc_get_stats'?
| 15956 |   .policy = qca_wlan_vendor_dcc_get_stats,
|       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |             qca_wlan_vendor_attr_dcc_get_stats
| rpb-dunfell/build-rpb-wayland/tmp-rpb_wayland-glibc/work/imx8mqevk-linaro-linux/kernel-module-qca6174/3.0-r0/git/CORE/HDD/src/wlan_hdd_cfg80211.c:15965:13: error: 'qca_wlan_vendor_dcc_clear_stats' undeclared here (not in a function); did you mean 'qca_wlan_vendor_attr_dcc_clear_stats'?
| 15965 |   .policy = qca_wlan_vendor_dcc_clear_stats,
|       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |             qca_wlan_vendor_attr_dcc_clear_stats
| rpb-dunfell/build-rpb-wayland/tmp-rpb_wayland-glibc/work/imx8mqevk-linaro-linux/kernel-module-qca6174/3.0-r0/git/CORE/HDD/src/wlan_hdd_cfg80211.c:15974:13: error: 'qca_wlan_vendor_dcc_update_ndl' undeclared here (not in a function); did you mean 'qca_wlan_vendor_attr_dcc_update_ndl'?
| 15974 |   .policy = qca_wlan_vendor_dcc_update_ndl,
|       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |             qca_wlan_vendor_attr_dcc_update_ndl
| rpb-dunfell/build-rpb-wayland/tmp-rpb_wayland-glibc/work/imx8mqevk-linaro-linux/kernel-module-qca6174/3.0-r0/git/CORE/HDD/src/wlan_hdd_cfg80211.c: In function '__wlan_hdd_cfg80211_scan':
| rpb-dunfell/build-rpb-wayland/tmp-rpb_wayland-glibc/work/imx8mqevk-linaro-linux/kernel-module-qca6174/3.0-r0/git/CORE/HDD/src/wlan_hdd_cfg80211.c:22920:8: warning: ISO C90 forbids variable length array 'chList' [-Wvla]
| 22920 |        char chList [(request->n_channels*5)+1];
|       |        ^~~~
| rpb-dunfell/build-rpb-wayland/tmp-rpb_wayland-glibc/work/imx8mqevk-linaro-linux/kernel-module-qca6174/3.0-r0/git/CORE/HDD/src/wlan_hdd_cfg80211.c: In function '__wlan_hdd_cfg80211_sched_scan_start':
| rpb-dunfell/build-rpb-wayland/tmp-rpb_wayland-glibc/work/imx8mqevk-linaro-linux/kernel-module-qca6174/3.0-r0/git/CORE/HDD/src/wlan_hdd_cfg80211.c:28751:9: warning: ISO C90 forbids variable length array 'chList' [-Wvla]
| 28751 |         char chList [(request->n_channels*5)+1];
|       |         ^~~~
| At top level:
| rpb-dunfell/build-rpb-wayland/tmp-rpb_wayland-glibc/work/imx8mqevk-linaro-linux/kernel-module-qca6174/3.0-r0/git/CORE/HDD/src/wlan_hdd_cfg80211.c:25078:20: warning: 'hdd_ieee80211_reason_code_to_str' defined but not used [-Wunused-function]
| 25078 | static const char *hdd_ieee80211_reason_code_to_str(uint16_t reason)
|       |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Peter Griffin <peter.griffin@linaro.org>