Revert "imx-base.inc: upgrade to gstreamer 1.20.2"
This reverts commit 912829e1aa543326682f45656b6240db97864655.

There is no downstream fork based on gstreamer 1.20.2.
Currently in meta-freescale master it is still 1.18.5.imx with non forked gstreamer components carried in meta-freescale at 1.18.5 for compatibility.

Prevents:
| WARNING: preferred version 1.20.2.imx of gstreamer1.0 not available (for item gstreamer1.0)
| WARNING: versions of gstreamer1.0 available: 1.18.5.imx 1.20.2
| ...

Fixes build of imx-gst1.0-plugin
| ERROR: imx-gst1.0-plugin-4.6.4-r0 do_compile: ExecutionError('... imx-gst1.0-plugin/4.6.4-r0/temp/run.do_compile.25172', 1, None, None)
|
| [1/37] aarch64-tdx-linux-gcc -mcpu=cortex-a72.cortex-a53 -march=armv8-a+crc -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/workdir/oe/tmp/work/cortexa72-cortexa53-mx8-tdx-linux/imx-gst1.0-plugin/4.6.4-r0/recipe-sysroot -Ilibs/libgstfsl-1.0.so.0.0.0.p -Ilibs -I../git/libs -I/workdir/oe/tmp/work/cortexa72-cortexa53-mx8-tdx-linux/imx-gst1.0-plugin/4.6.4-r0/recipe-sysroot/usr/include/gstreamer-1.0 -I/workdir/oe/tmp/work/cortexa72-cortexa53-mx8-tdx-linux/imx-gst1.0-plugin/4.6.4-r0/recipe-sysroot/usr/include/glib-2.0 -I/workdir/oe/tmp/work/cortexa72-cortexa53-mx8-tdx-linux/imx-gst1.0-plugin/4.6.4-r0/recipe-sysroot/usr/lib/glib-2.0/include -I/workdir/oe/tmp/work/cortexa72-cortexa53-mx8-tdx-linux/imx-gst1.0-plugin/4.6.4-r0/recipe-sysroot/usr/include/orc-0.4 -I/workdir/oe/tmp/work/cortexa72-cortexa53-mx8-tdx-linux/imx-gst1.0-plugin/4.6.4-r0/recipe-sysroot/usr/include/imx -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -U_FILE_OFFSET_BITS -DARM -D_GUNC_ -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/workdir/oe/tmp/work/cortexa72-cortexa53-mx8-tdx-linux/imx-gst1.0-plugin/4.6.4-r0=/usr/src/debug/imx-gst1.0-plugin/4.6.4-r0 -fdebug-prefix-map=/workdir/oe/tmp/work/cortexa72-cortexa53-mx8-tdx-linux/imx-gst1.0-plugin/4.6.4-r0=/usr/src/debug/imx-gst1.0-plugin/4.6.4-r0 -fdebug-prefix-map=/workdir/oe/tmp/work/cortexa72-cortexa53-mx8-tdx-linux/imx-gst1.0-plugin/4.6.4-r0/recipe-sysroot= -fdebug-prefix-map=/workdir/oe/tmp/work/cortexa72-cortexa53-mx8-tdx-linux/imx-gst1.0-plugin/4.6.4-r0/recipe-sysroot-native= -fPIC -pthread -DUSE_X11 -MD -MQ libs/libgstfsl-1.0.so.0.0.0.p/gstimxcommon.c.o -MF libs/libgstfsl-1.0.so.0.0.0.p/gstimxcommon.c.o.d -o libs/libgstfsl-1.0.so.0.0.0.p/gstimxcommon.c.o -c ../git/libs/gstimxcommon.c
| FAILED: libs/libgstfsl-1.0.so.0.0.0.p/gstimxcommon.c.o
| aarch64-tdx-linux-gcc -mcpu=cortex-a72.cortex-a53 -march=armv8-a+crc -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/workdir/oe/tmp/work/cortexa72-cortexa53-mx8-tdx-linux/imx-gst1.0-plugin/4.6.4-r0/recipe-sysroot -Ilibs/libgstfsl-1.0.so.0.0.0.p -Ilibs -I../git/libs -I/workdir/oe/tmp/work/cortexa72-cortexa53-mx8-tdx-linux/imx-gst1.0-plugin/4.6.4-r0/recipe-sysroot/usr/include/gstreamer-1.0 -I/workdir/oe/tmp/work/cortexa72-cortexa53-mx8-tdx-linux/imx-gst1.0-plugin/4.6.4-r0/recipe-sysroot/usr/include/glib-2.0 -I/workdir/oe/tmp/work/cortexa72-cortexa53-mx8-tdx-linux/imx-gst1.0-plugin/4.6.4-r0/recipe-sysroot/usr/lib/glib-2.0/include -I/workdir/oe/tmp/work/cortexa72-cortexa53-mx8-tdx-linux/imx-gst1.0-plugin/4.6.4-r0/recipe-sysroot/usr/include/orc-0.4 -I/workdir/oe/tmp/work/cortexa72-cortexa53-mx8-tdx-linux/imx-gst1.0-plugin/4.6.4-r0/recipe-sysroot/usr/include/imx -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -U_FILE_OFFSET_BITS -DARM -D_GUNC_ -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/workdir/oe/tmp/work/cortexa72-cortexa53-mx8-tdx-linux/imx-gst1.0-plugin/4.6.4-r0=/usr/src/debug/imx-gst1.0-plugin/4.6.4-r0 -fdebug-prefix-map=/workdir/oe/tmp/work/cortexa72-cortexa53-mx8-tdx-linux/imx-gst1.0-plugin/4.6.4-r0=/usr/src/debug/imx-gst1.0-plugin/4.6.4-r0 -fdebug-prefix-map=/workdir/oe/tmp/work/cortexa72-cortexa53-mx8-tdx-linux/imx-gst1.0-plugin/4.6.4-r0/recipe-sysroot= -fdebug-prefix-map=/workdir/oe/tmp/work/cortexa72-cortexa53-mx8-tdx-linux/imx-gst1.0-plugin/4.6.4-r0/recipe-sysroot-native= -fPIC -pthread -DUSE_X11 -MD -MQ libs/libgstfsl-1.0.so.0.0.0.p/gstimxcommon.c.o -MF libs/libgstfsl-1.0.so.0.0.0.p/gstimxcommon.c.o.d -o libs/libgstfsl-1.0.so.0.0.0.p/gstimxcommon.c.o -c ../git/libs/gstimxcommon.c
| ../git/libs/gstimxcommon.c:21:10: fatal error: gstimxcommon.h: No such file or directory
|    21 | #include "gstimxcommon.h"
|       |          ^~~~~~~~~~~~~~~~
| compilation terminated.

Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>
(cherry picked from commit c35ef4115ad93a4b940f1ae5fb3cc9ac1920eab3)