imx-alsa-plugins: Make imx7ulp a compatible machine
>From [1] we know the imx-alsa-plugins_1.0.26 does support all imx7, and
it is defined in the BSP as MACHINE_EXTRA_RRECOMMENDS, so this patch add
imx7ulp as compatible.

It also fixes the following error (when building for imx7ulpevk):

ERROR: Nothing RPROVIDES 'imx-alsa-plugins' (but
/home/daiane/code/yocto/master/sources/poky/meta/recipes-core/images/core-image-base.bb,
/home/daiane/code/yocto/master/sources/poky/meta/recipes-core/packagegroups/packagegroup-base.bb
RDEPENDS on or otherwise requires it)
imx-alsa-plugins was skipped: incompatible with machine imx7ulpevk (not
in COMPATIBLE_MACHINE)

[1]
https://source.codeaurora.org/external/imx/meta-fsl-bsp-release/tree/imx/meta-bsp/recipes-multimedia/alsa/imx-alsa-plugins_1.0.26.bb?h=rocko-4.9.88-2.0.0_ga

Signed-off-by: Daiane Angolini <daiane.angolini@nxp.com>
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>