imx-test: fix ALLOW_EMPTY error
the package name needs to be specified else we get :
ERROR: QA Issue: .../imx-test_00.00.00.bb: Variable ALLOW_EMPTY is set as not being package specific, please fix this.

Signed-off-by: Eric Bénard <eric@eukrea.com>