imx-gpu-viv: Fix i.MX 8 and 8X binary compatibility
The removal of gl32.h for 8QXP can cause build breaks in a multi-machine
build folder like the following:

| .../build/tmp/work/imx8qxpmek-poky-linux/gstreamer1.0-plugins-good-qt/1.14.4.imx-r0/recipe-sysroot/usr/include/QtGui/qopengl.h:105:13: fatal error: GLES3/gl32.h: No such file or directory
|  #   include <GLES3/gl32.h>

To make the ABI safe for 8 and 8X, which have a shared PACKAGE_ARCH,
provide gl32.h in both cases. The lack of support can then be handled
by a runtime error.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>