glslang: Align with Vulkan downgrade 1.3.275.0.imx
The current glslang fails to compile.
```
| /.../SPIRV/SpvTools.cpp: In function 'spv_target_env glslang::MapToSpirvToolsEnv(const SpvVersion&, spv::SpvBuildLogger*)':
| /.../SPIRV/SpvTools.cpp:75:32: error: 'SPV_ENV_VULKAN_1_4' is not a member of 'spv_target_env'
|    75 |         return spv_target_env::SPV_ENV_VULKAN_1_4;
|       |                                ^~~~~~~~~~~~~~~~~~
| /.../SPIRV/SpvTools.cpp: In function 'void glslang::SpirvToolsValidate(const TIntermediate&, std::vector<unsigned int>&, spv::SpvBuildLogger*, bool)':
| /.../SPIRV/SpvTools.cpp:168:5: error: 'spvValidatorOptionsSetAllowOffsetTextureOperand' was not declared in this scope
|   168 |     spvValidatorOptionsSetAllowOffsetTextureOperand(options, intermediate.usingTextureOffsetNonConst());
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Downgrade to 1.3.275.0 to align with the existing Vulkan downgrade.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>
(cherry picked from commit 5717bf74121ca3f0c6d3c7c8194e85e0626f0760)