libimxvpuapi2: Bump revision to 8639837a246f
After bumping gstreamer1.0-plugins-imx build is failing. Here is a snippet
of the build error:

| ../git/ext/vpu/gstimxvpuenc.c:473:20: error: 'ImxVpuApiEncOpenParams'
has no member named 'fixed_intra_quantization'
|         open_params->fixed_intra_quantization =
imx_vpu_enc->fixed_intra_quantization;
|                    ^~

Fix it by updating libimxvpuapi2 to the current HEAD of its repository.

Signed-off-by: Hiago De Franco <hiago.franco@toradex.com>
(cherry picked from commit c27889664be1cb62926c19c619838882367136c5)