waffle: Add missing dependency on EGL
For Wayland builds without XWayland support, the following
build break was happening:

In file included from /home/bamboo/build/5.4-zeus-full/fsl-imx-internal-wayland/temp_build_dir/build_fsl-imx-internal-wayland/tmp/work/aarch64-mx8-poky-linux/waffle/1.6.0-r0/recipe-sysroot/usr/include/EGL/egl.h:39,
                 from ../waffle-1.6.0/src/waffle/egl/wegl_context.h:31,
                 from ../waffle-1.6.0/src/waffle/egl/wegl_util.c:28:
/home/bamboo/build/5.4-zeus-full/fsl-imx-internal-wayland/temp_build_dir/build_fsl-imx-internal-wayland/tmp/work/aarch64-mx8-poky-linux/waffle/1.6.0-r0/recipe-sysroot/usr/include/EGL/eglplatform.h:144:10: fatal error: X11/Xlib.h: No such file or directory
  144 | #include <X11/Xlib.h>
      |          ^~~~~~~~~~~~
compilation terminated.

This happens because the egl.pc configuration is missing.

Fix the mising dependency.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>
(cherry picked from commit eea3e3bbe0870b46363884402c97b4f1b187a6f9)